# 服务提供者，springCloud是通过rest请求来远程调用服务的server:
server:
  port: 8080
# 应用实例名
spring:
  application:
    name: eureka-provider

eureka:
  instance:
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址,如果不配置就是机器的主机名。
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
