server:
      port: 8082
#spring:
#  profiles:
#    active: test

---
spring:
  profiles: dev
server:
  port: 8083

---
spring:
  profiles: test
server:
  port: 8084

---
# 值前面必须有空格
#person:
    lastName: hello
    age: 18
    flag: false
    birth: 2018/10/10
    maps: {k1: v1,k2: v2}
    lists:
      - lisi
      - wangwu
    dog:
      name: 小狗
      age: 12
